#+TITLE: Teil 1 der gestreckten Abschlussprüfung "Einrichten eines IT-gestützten Arbeitsplatz"
#+OPTION: toc=nil

* Projektmanagment
Ein Projekt ist ein einmaliges Vorhaben mit einem definiertem Ziel über einen festgelegten Zeitraum.

Dieses Ziel sollte nach den *SMART*-Kriterien definiert werden:
+ *S* Spezifisch  :: Eindeutig und Konkret, sodass alle im  Projektteam das gleiche Ziel vor Augen haben
+ *M* Messbar     :: Es ist feststellbar, ob das Ziel erreicht wurde
+ *A* Akzeptiert  :: Das Ziel wurde vom Projektteam als erstrebenswert bewertet
+ *R* Realistisch :: Das Ziel wurde vom Projektteam als erreichbar bewertet
+ *T* Terminiert  :: Das Ziel muss bis zu einem bestimmten Zeitpunkt erreicht werden

Die drei wichtigsten Kenngrößen für ein Projekt sind Kosten, Zeit und Qualität. Diese sind voneinander Abhängig und bilden so das "Magische Dreieck". Reduziere ich die Zeit, so reduziere ich auch die Qualität oder die Kosten. 

An einem Projekt sind oft zwei oder mehr Parteien beteiligt, welche untereinander und an das Projekt verschidene Ansprüche haben. Diese werden Stakeholder genannt. Stakeholder sind:
+ Unternehmensleitung
+ Projektleitung
+ Projektmitarbeiter/Arbeitnehmer
+ Kunden
+ Dienstleister & Lieferanten
+ Staatliche Institutionen

Projekte lassen sich in 4 Phasen einteilen:
1. Projektdefinition   :: In der Projektdefinition wird das Ziel mittels einer *Machbarkeitsstudie* festgelegt.  
2. Projektplanung      :: In der Projektplanung wird der zeitliche Ablauf des Projekt mittels eines *Gantt-Diagramm* auf die Deadline ausgerichtet.
3. Projektdurchführung :: In der Projektdurchführung werden die einzelene Arbeitsschritte ausgeführt. Die erreichten Zwischenergebnisse werden *Meilensteine* genannt.
4. Projektabschluss    :: Zum Projektabschluss wird das Gesamtergebniss in einem *Abschlussbericht* dokumentiert.

Während der Projektdefinition wird das Ziel mittels einer *Machbarkeitsstudie* festgelegt. Die Machbarkeitsstudie ist eine Umfangreiche Studie, welche das Projekt aus technischer und wirtschaftlicher untersucht und die verschidenen Perspektiven der Projektteilnehmer betrachtet. Die Stakeholderanalyse und die Risikoanalyse sind Bestandteil der Machbarkeitsstudie.
+ Stakeholderanalyse :: Zeigt die Erwartungen der einzelnen Projektbeteiligten und identifiziert Probleme wie z.B. gegenläufige Ziele
+ Risikoanalyse :: Die Risikoanalyse identifiziert Probleme, die während eins Projekts auftreten können.

Während des Projekt ist es wichtig die Stakeholder und Risiken zu verwalten. Beim Stakeholder-Managment werden die werden die Stakeholder regelmäßig analysiert und die erwartungen dokumentiert. 

Das Risikomanagement befasst sich mit folgenden Schritten:
1. Identifikation :: Beschreibung ihrer Art und ihrer Ursachen.
2. Analyse :: Eintrittswahrscheinlichkeit und Auswirkungen.
3. Priorisierung :: Aufgrundlage der Analyse die werden die Risiken nach vorgegebenen Kriterien bewertet.
4. Bewältigung :: Maßnahmen um die Eintrittswahrscheinlichkeit oder die Auswirkungen zu minimieren.
5. Überwachung :: Überwachung der Eintrittswahrscheinlichkeit.

** Netzplan
Im Netzplan werden alle Vorgänge eines Projekts nach ihren Abhängigkeiten und Reihenfolgen verkettet und grafisch dargestellt. Er stellt einen ersten Entwurf eines Ablaufplans dar und gibt Informationen darüber, wie Vorgänge verschoben werden können. Zudem können zeitkritische Vorgänge identifiziert werden und als kritische Pfad markiert werden.
Im Netzplan gibt es folgende Objekte:
+ Vorgangskonten
    - Vorgangsbezeichner oder Vorgangsnummer
    - D :: Vorgangsdauer
    - FAZ :: frühester Anfangszeitpunkt
    - FEZ :: frühester Endzeitpunkt (FEZ = FAZ + D)
    - SAZ :: spätester Anfangszeitpunkt (SAZ = SEZ - D)
    - SEZ :: spätester Endzeitpunkt 
    - GP :: Gesamtpuffer beschreibt, wie weit ein Vorgang verschoben oder verlängert werden kann, ohne das es Einfluss auf das Projektende hat. (GP =  SEZ - FEZ)
    - FP :: freier Puffer beschreibt, wie weit ein Vorgang verschoben oder verlängert werden kann, ohne das es Einfluss auf die benachbarten Vorgänge hat. (FP = FAZ nachfolger - FEZ Vorgänger)
    - kritische Pfad :: Der Kritische Pfad beschreibt alle Knoten, bei den eine Verzögerung direkten Einfluss auf das Projektende hat. Jeder Vorgang mit einem Gesamtpuffer von 0 liegt auf dem kritischen Pfad. Diese Vorgänge bestimme die Gesamtprojektdauer.
+ Anordnungsbeziehungen

Erstellen eines Netzplan:
1. Erstellen einer Vorgangsliste
    + Vorgänge nach Reihenfolge nummerieren
    + Vorgängen ihre direkten Vorgänger zuordnen
    + Vorgänge aufsteigend nach Vorgangsnummer sortieren
1. Aktionen als Vorgangskonten darstellen. Bezeichner und Dauer eintragen
2. Vorgangsknoten mit Anordnungsbeziehungen verknüpfen. Jede Anordnungsbeziehung ist eine eigene Linie
3. Vorwärtsterminierung:
    + Erster Knoten bekommt einen FAZ von 0
    + FEZ = FZA + D
    + FZA der Nachfolger bestimmen: max(FEZ Vorgänger)
4. Rückwärtsterminierung:
    + Beim letzten Knoten die FEZ als SEZ setzen
    + SAZ = SEZ - D
    + SEZ der Vorgänger bestimmen: min(SAZ Nachfolger)
5. Pufferzeiten berechnen
    + GP = SEZ - FEZ
    + FP = FAZ Nachfolger - FEZ Vorgänger
6. Kritischer Pfad markieren. Alle Knoten mit einem GP von 0 bilden den Kritischen Pfad

Im Netzplan gibt es keine genaue zeitliche Einordnung.

Der Nachteil des Netzplan ist, das er nicht Intuitiv zu lesen und zu verstehen ist. Als Gantt-Diagramm ist die Darstellung intuitiver zu verstehen.
** Gantt-Diagramm
Im Gantt-Diagramm werden alle Vorgänge eines Projekts nach ihren Abhängigkeiten und Reihenfolgen verkettet und grafisch dargestellt. Er stellt einen weiteren Entwurf eines Ablaufplans dar und gibt Informationen darüber, wie Vorgänge verschoben werden können. Zudem können zeitkritische Vorgänge identifiziert werden und als kritische Pfad markiert werden. Zu guter letzt ermöglicht das Gantt-Diagramm die Kalendrierung durch das festlegen eines Startzeitpunktes. Gibt es einen Netzplan, so kann dieser sehr leicht als Gantt-Diagramm dargestellt werden.

Erstellen eines Gantt-Diagramm
1. Erstellen einer Vorgangsliste
    + Vorgänge nach Reihenfolge nummerieren
    + Vorgängen ihre direkten Vorgänger zuordnen
    + Vorgänge aufsteigend nach Vorgangsnummer sortieren
[[https://www.youtube.com/watch?v=EVDuXXzl4ZY]]


** Wasserfallmodelle
Das Wasserfallmodell ist ein lineares Vorgehensmodel für die durchführung von Projekten. In einem Top-Down Ansatz wird das Projekt von einem von einem abstrakten Startpunkt zu einem konkreten Ziel gebracht. Dafür wird das Projekt in verschidene Phasen eingeteilt:
1. Planung (Lastenheft & Projektplan) :: Der Auftraggeber definiert, unter möglicher einbeziehung des Auftragnehmers, die Anforderungen ( *Was & Wofür* ) an die Software und die zeitliche Entwicklung und die Meilensteine des Projekts
2. Definition (Pflichtenheft) :: Der Auftragnehmer definiert in konkreter Form, *wie & womit* er die Anforderungen im Pflichtenheft umsetzen wird.
3. Design (Softwarearchitektur) :: Der Auftragnehmer erstellt Struktogramme, die die Softwarearchitektur beschreiben.
4. Implementierung (Programmierung & Modultests) :: Der Auftragnehmer erstellt die Software
5. Test (Testprotokoll) :: Der Auftragnehmer teste, gegebenenfalls in Zusammnenarbeit mit dem Auftraggeber, die Software
6. Einsatz & Wartung (Abnahmeprotokoll & Servicerequests) :: Der Auftragnehmer nimmt die Software in Betrieb. Im Laufe der Betriebszeit gefundene Fehler werden gemeldet und behoben.

Vorteile:
+ Klare Abgrenzungen der Phasen
+ Einfache Planung und Kontrolle
+ Klare Abschätzung von Kosten und Umfang bei stabilen Anforderungen

Nachteile:
+ Unflexibel bei Änderngen der Anforderungen
+ Fehler die in einer frühen Phase gemacht wurden, können unentdeckt bleiben und können so nur unter hohm aufwand entfernt werden.
+ Phasen laufen theoretisch nacheinander ab, Rückschritte sind in der Entwicklung aber unvermeidbar

** Agile Softwareentwicklung
Die agile Softwareentwicklung orientiert sich am agilen Manifest, welches 2001 von 17 Informatikern verfasst wurde. Das Manifest formuliert vier Leitsätze und zwölf Prinzipen für die Softwareentwicklung.

#+BEGIN_QUOTE
„Wir erschließen bessere Wege, Software zu entwickeln, indem wir es selbst tun und anderen dabei helfen. Durch diese Tätigkeit haben wir diese Werte zu schätzen gelernt:
+ *Individuen und Interaktionen* sind wichtiger als Prozesse und Werkzeuge
+ *Funktionierende Software* ist wichtiger als umfassende Dokumentationen
+ *Zusammenarbeit mit dem Kunden* ist wichtiger als Vertragsverhandlungen
+ *Reagieren auf Veränderung* ist wichtiger als das Befolgen eines Plans
Das heißt, obwohl wir die Werte auf der rechten Seite wichtig finden, schätzen wir die Werte auf der linken Seite höher ein.“
#+END_QUOTE

Die Prinzipien lauten:
+ Unsere höchste Priorität ist es, den Kunden durch frühe und kontinuierliche Auslieferung wertvoller Software zufrieden zu stellen.
+ Heiße Anforderungsänderungen selbst spät in der Entwicklung willkommen. Agile Prozesse nutzen Veränderungen zum Wettbewerbsvorteil des Kunden.
+ Liefere funktionierende Software regelmäßig innerhalb weniger Wochen oder Monate und bevorzuge dabei die kürzere Zeitspanne.
+ Fachexperten und Entwickler müssen während des Projektes täglich zusammenarbeiten.
+ Errichte Projekte rund um motivierte Individuen. Gib ihnen das Umfeld und die Unterstützung, die sie benötigen und vertraue darauf, dass sie die Aufgabe erledigen.
+ Die effizienteste und effektivste Methode, Informationen an und innerhalb eines Entwicklungsteams zu übermitteln, ist im Gespräch von Angesicht zu Angesicht.
+ Funktionierende Software ist das wichtigste Fortschrittsmaß.
+ Agile Prozesse fördern nachhaltige Entwicklung. Die Auftraggeber, Entwickler und Benutzer sollten ein gleichmäßiges Tempo auf unbegrenzte Zeit halten können.
+ Ständiges Augenmerk auf technische Exzellenz und gutes Design fördert Agilität.
+ Einfachheit -- die Kunst, die Menge nicht getaner Arbeit zu maximieren -- ist essenziell.
+ Die besten Architekturen, Anforderungen und Entwürfe entstehen durch selbstorganisierte Teams.
+ In regelmäßigen Abständen reflektiert das Team, wie es effektiver werden kann und passt sein Verhalten entsprechend an.

Aus diesen Erkenntnissen wurden eine Reihe an verschiedenen agilen Methoden entwickelt.

*** Agile Methoden
Eine Methode ist ein formalisierter, allgemeiner Ablauf, der sich bewährt hat.
+ Extreme Programming
+ Pragmatic Programming
+ Kanban
+ Crystal
+ Feature Driven Development
+ Scrum
*** Scrum
Scrum ist die wohl bekannteste agile Methode. Bei Scrum steht ein iterative Ansatz im Vordergrund, der den Entwicklungsprozess in Sprints einteilt. Ein Sprint ist eine Zeiteinheit von min. einer Woche bis max. vier Wochen. Zudem definiert Scrum die drei Rollen Productowner, Scrummaster und Team, welche verschidene funktionen innerhalb der Einzelen Phasen einse Sprint inne haben.

1. Product Backlog :: Der Product Owner bildet eine Schnittstelle zwischen dem Team und dem Kunden. Er initiiert das Product Backlog, indem er, auch in zusammenarbeit mit den Stakeholdern (Kunden, Investoren, dem Team, etc.), einen ersten Lösungsversuch definiert.
2. Sprint Planning & Sprint Backlog :: Bevor der Sprint gestartet wird,muss der Sprint geplant werden. Dafür wird vom Productowner der Product Backlog vorgestellt. Das Team entscheidet selbständig, welche und wieviele Anforderungen sie in Ihren Sprint Backlog übernimmt und im kommenden Sprint umsetzen will. Die Anforderungen werden schlussendlich in Tasks herrunter gebrochen.
3. Sprint & Daily Scrum :: Während des Sprint wird das Sprint Backlog und die daraus resultierenden Tasks abgearbeitet. Integraler bestandteil des Sprint ist das Daily Scrum, ein tägliches, sehr kurzes Meeting, in welchem jedes Mitglied des Teams mitteilt, was er gemacht hat, was er machen wird und welche Probleme es gibt, um das Team auf einen einheitliche Stand zu bringen. Der Sprint wird vom Scrum Master betreut. Er sorgt dafür, das die Scrum Regeln eingehalten werden und das das Team möglichst Barrierefrei arbeiten kann.
4. Sprint Review :: Im Sprint Review wird das Inkrement, das Zwischenergebnisse, vom Product Owner, gegebenen falls in zusammenarbeit mit Kunden, gegen die Anforderungen aus dem Product Backlog geprüft. Der Product Owner nutzt das Review zudem um das Backlog zu aktualisiern und als Startpunkt für das nächste Sprint Planing verfügbar zu machen.
5. Sprint Retroperspective :: Im letzten Meeting vor dem Prozessneustart setzten sich Team, Scrum Master und evtl. auch der Product Owner zusammen um zu besprechen, an welchen stellen der nächste Sprint verbessert werden kann.

+ Scrum hat die Rollen Product Owner, Scrum Master und Team.
+ Ein Sprint dauert zwischen einer und vier Wochen.
+ Ein Sprint besteht aus den Phasen Sprint Planning, Sprint, Sprint Review und Sprint Retroperspective.
+ Der Product Owner ist eine Schnittstelle zwischem dem Team und Stakeholdern.
+ Der Product Owner ist für das Product Backlog zuständig.
+ Der Product Backlog ist eine organisierte Übersicht über die Anforderungen an das Produkt.
+ Der Scrum Master unterstützt das Team, sodass es ungestört arbeiten kann.
+ Das Team besteht aus min. 3 Personen und sollte max. 10 Personen haben.
+ Das sollte aus verschiedensten Experten bestehen.
+ Über das Daily Scrum wird das Team auf einen einheitlichen Informationsstand gesetzt.
+ Stakeholder können jederzeit in den Prozess eingebunden werden.

*** Agile Prozesse
Ein Prozess ist der Verlauf eines Projekts über einen bestimmten Zeitraum. Der agile Prozess hat zum Ziel, schnell ein Ergebnis zu erreichen, welches mit dem Kunden abgestimmt werden kann. Dabei kommen agile Methoden zum einsatzt.

* Qualitätsmanagment
Produkte und dazugehörige Dienstleistungen haben eine bestimmte Qualität. Anhand der Qualität kann man bestimmen, in wie weit die inhärenten Merkmale eines Produkt die Anforderungen erfüllen. Das Qualitätsmanagment überwacht und verbessert die Prozesse und organisatorische Maßnamen innerhalb der Entwicklung und der Dienstleistungen um in diesen ein möglichst hohe Qualität zu erreichen.

Innerhalb eines Unternehmens sollte ein Qualitätsmanagmentsystem eingerichtet sein, welches Rollen und Verantwortlichtekeiten festlegt sowie die Prozesse definiert und dokumentiert. Es gibt verschidene Philosopien, wie ein Qualitätsmanagentsystem auszusehen hat. Beispiele hierfür sind das Total-Quality-Model *TQM* und dessen Weiterentwicklung *EFQM-Modell* (European Foundation for Quality Managment-Modell).

Die Sieben Grundsätze des Qualitätmanagments:
+ Kundenorientiert
+ Verantwortlichkeit der Führung
+ Einbeziehung der beteiligten Personen
+ Prozessorientierter Ansatz
+ Kontinuierliche Verbesserung
+ Sachbezogene Entscheidungsfindung
+ Lieferantenbeziehungen zum gegenseitigen Nutzen.

Die DIN EN ISO 9000ff definiert ein weltweit einheitlichen Standard für Qualitätsmanagmentsystem. Größtenteils definiert diese Norm Prozesse, Produkte und Dienstleisungen und deren Verbesserung, aber auch den Umgang mit Kunden, Lieferanten und Mitarbeitern. Firmen können die Normerfüllung ihres Qualitätsmanagment durch Auditoren prüfen und zertifizieren lassen.

Normen
+ DIN :: Deutsch Industrie Norm
+ EN :: Europäische Norm
+ ISO :: International Organisation für Normung
+ ICE :: International Electrotechnical Commission

+ Qualitätsaspekte
  - Philosophien
    + TQM Total-Quality-Managment-Model
    + EFQM European Foundation Quality Managment Model
  - Normen
    + DIN EN ISO 9000ff
      - DIN EN ISO 9001
      - DIN EN ISO 9004
  - Qualitätsbegriff
    + Prozessqualität
    + Produktqualität
      - Inhärentes Merkmal
  - Qualitätsmanagment
    + Qualitätspolitik :: In der Qualitätspolitik erstellen Unternehmen unter berücksichtigung ihrer Qualitätsziele die Rahmenbedingungen für alle weiteren Aktivitäten des Qualitätsmanagment.
    + Qualitätsplanung :: In der Qualitätsplanung wird anhand des Ist-Zustand die Prozesse(Ablauforganisation) & Strukturen(Aufbauorganisation) gestaltet und der Soll-Zustand definiert. 
    + Qualitätslenkung :: In der Qualitätslenkung werden die in der Qualitätsplanung gestalteten Prozesse umgesetzt.
    + Qualitätsprüfung :: In der Qualitätsprüfung wird ausgewertet, ober der gewünschte Soll-Zustand erreicht wurde. 
    + Qualitätssicherung :: In der Qualitätssicherung werden aus der Qualitätsplanung, Qualitätslenkung & Qualitätsprüfung gewonnenen Informationen genutz, um die Prozesse und Strukturen zu verbessen. 
** Qualitätsmanagmentsysteme
Die Einführung eines Qualitätsmanagmentsysteme passiert in folgenden Schritten
+ Ist-Analyse
+ Soll-Konzept
+ QM-Handbuch erstellen
+ Mitarbeiterschulung
+ Interner Audit
+ Externer Audit & Zertifizierung
** TQM & EFQM
Total Quality Managment ist eine Philosopie, die unternehmensweit ein Klima der Verbesserung von Prozessen, Strukturen und personellen Fähigkeiten etabliert um Produkte und Dienstleistungen höchster Qualität zu erstellen. Die Unternehmensleitung ist in diesem Ansatz dazu verpflichtet die Qualität durch Zielsetzung und Finanzierung von Personaleinsatz und Schulungen aktiv zu verwalten.

European Foundation Quality Managment ist eine weiterentwickelte dieser Philosopie.

Beide Philosopien werden durch die Schaffung der Norm DIN EN ISO 9000ff überschattet und quasie formalisiert.  

** DIN EN ISO 9000ff.
** Softwarequalität
Software hat folgende Qualitätsmerkmale:
+ Zuverlässigkeit :: Zuverlässigkeit beschreibt wie reif eine Software ist im Bezug auf Fehlertolerenz während der Laufzeit und der Wiederherstellbarkeit der Arbeitsfähigkeit.
+ Funktionalität :: Funktionalität beschreibt die Umsetzung der Anforderungen.
+ Benutzbarkeit :: Benutzbarkeit beschreibt, wie einfach die Software zu bedinen und zu erlenen ist.
+ Effizenz :: Effizenz beschreibt das Zeitverhalten und Verbrauchsverhalten.
+ Wartbarkeit :: Wartbarkeit beschreibt, wie einfach der Programmcode zu analysieren und zu änderne ist.
+ Portabilität :: Portabilität beschreibt die Instaliebarkeit auf verschiedenen Plattformen, Austauschbarkeit verschidener Komponenten und die Anbindung andere Systeme

Um die Qualität einer Software sicher zu stellen, sind verschidene Tests nötig
+ Unit/Modultests :: Der Unittest dient dazu eine Module/Unterprogramme/Komponenten oder Klassen auf Lauffähigkeit und Korrekte (Teil)Ergebnisse zu überprüfen.
+ Integrationstest :: Der Integrationstest testet die Zusammenarbeit voneinander abhängiger Komponente und deren Schnittstellen auf korrekte Ergebnisse über komplette Abläufe.
+ Systemtest :: Beim Systemtest wird das gesamte System gegen alle funktionalen und nicht-funktionalen Anforderungen auf einem Testsystem, welches die Produktivumgebung simuliert, getestet.
+ Abnahmetest :: Der Abnahmetest wird durch den Auftraggeber durchgefühert und testet genau wie der Systemtest alle funktionalen und nicht-funktionalen Anforderungen.

Tests kann man in *White-Box* und *Black Box* Test einteilen. Beim White-Box Test sind dem Tester die Funktion sowie deren Implementation bekannt, beim Black-Box Test sind dem Tester die inneren Abläufe nicht bekannt.

** Barrierefreiheit
*** Barrierefreiheit
Das *Behindertengleichstellungsgesetzt* und die daraus folgenden *Barrierefreie-Informationstechnik-Verordnung - BITV 2.0* hat zum Ziel, das moderne Informations- und Kommunikations-System grundsätzlich barrierefrei gestaltet werden. Im IT-Bereich bedeutet Barrierefreiheit, dass Betriebssystem, Anwendungen und Websites auch von Menschen mit körperlichen Einschränkungen bedient werden können. Maßnahmen hierfür sind:
+ Strukturierung und Aussagekräftige Überschriften 
+ Navigierbarkeit ohne Maus
+ Alternativtexte für Bilder
+ Texte sind skalierbar

* Datenschutz
Datenschutz befasst sich mit dem Schutz von Persönlichkeitsrechten während IT/Daten-Sicherheit sich mit dem Schutz von Daten beschäftigt.

Der Datenschutz befasst sich mit dem Schutz von Persönlichkeitsrechten durch die Verarbeitung und Speicherung von personenbezogenen Daten und wird durch die *Datenschutz-Grundverordung - DSGVO* der EU und dem daraus resultierenden *Bundesdatenschutzgesetzt - BDSG* und *Landesdatenschutzgesetze* geregelt. Die *DSGVO* bietet Personen folgende Rechte:
+ Recht auf Auskunft :: Eine Person hat das Recht zu erfahren, welche Daten gespeichert und verarbeitet werden, den Verarbeitungszweck, die Datenherkunft und Weitergabe sowie die Dauer der Speicherung.
+ Recht auf Berichtigung :: Eine Person hat das Recht auf sofortige Berichtigung falscher Daten.
+ Recht auf Löschung :: Eine Person hat das Recht auf die Löschung von Daten,
	- wenn der Verarbeitungszweck nicht mehr gegeben ist.
	- wenn die Person ihre Einwilligung mit allen Konsequenzen wiederruft.
	- wenn die Daten unrechtmäßig erhoben wurden.
	
Hat ein Unternehmen mit personenbezogenen Daten zu tun, muss ein Datenschutzbeauftragter ernannt werden, wenn min. einer der folgenden Punkte zutrifft:
+ Min. 20 Mitarbeiter arbeiten dauerhaft mit der automatisierten Verarbeitung von personenbezogenen Daten.
+ Der Verarbeitungszweck liegt bei der Erfassung von Daten zu Herkunft, Religion, politischer Anschauung oder Gesundheit.
+ Der Verarbeitungszweck birgt ein hohes Risiko für die Rechte und Freiheiten der betroffenen Personen.
+ Daten werden geschäftsmäßig erhoben und weitergegeben.
+ Der Verarbeitungszweck liegt bei der systematischen und umfangrichen Überwachung der betroffenen Personen.

** Standard-Datenschutzmodelle
Die Einhaltung der Rechtsvorschrifften können mit des Standard-Datenschutzmodell überprüft werden. Dafür definiert das Modell sieben Gewährleistungsziele:
+ Datenminimierung :: Die Datenmenge zu einer Person muss so gering wie möglich gehalten werde. Dies wird dadurch erreicht,
	- das nur Daten erhoben werden, die benötigt werden.
	- das Daten nur solange gespeichert werden wie nötig
+ Verfügbarkeit :: Der Zugriff auf die Daten und die ordnungsgemäße Verwendung in den zugeordenten Prozessen ist unverzüglich möglich. Dies wird erreicht durch
	- eine hohe Belastbarkeit des Systens durch Redundanzen in Hard- und Software sowie Infrastruktur
	- die Wiederherstellbarkeit von Datenständen durch Datensicherungen
+ Integrität :: Die Daten müssen vollständig, richtig und aktuell bleiben. Abweichungen sollten aussgeschlossen sein oder müssen feststellbar sein, damit sie korrigiert werden können. Dies wird erreicht durch,
	- die Einschränkung von Schreib- und Änderungsrechte in der Standardrechteverwaltung
	- die Dokumentation von Rollen und Berechtigungen in einem Rollenkonzept
	- die Dokumentation von Änderungen in Zugriffskontrolllisten
+ Vertraulichkeit :: Die personenbezogenen Daten sind vor der Einsicht und Verwendung unautorisierter Personen geschützt durch
	- die Dokumentation von Rollen und Berechtigungen in einem Rollenkonzept
	- die Dokumentation von Änderungen in Zugriffskontrolllisten
+ Nichtverkettung :: Personenbezogene Datenbestände die für unterschiedliche Verwendungszwecke erhoben wurden dürfen nicht zusammengeführt werden. Dies wird erreicht durch
	- die Einschränkung von Verarbeitungs-, Nutzungs- & Übermittlungs-Rechten
	- Schließen von Schnittstellen bei Verarbeitungsverfahren und Komponenten
+ Transparenz :: Betroffene Personen, der Systembetreiber und Kontrollinstanzen können erkennen, wann welche Daten für welchen Verwendungszweck erhoben und mit welchen Prozess verarbeitet wurde sowie wohin die Daten weitergeleitet werden. Hierfür werden Verarbeitung- & Geschäfts-Prozesse, Datenbestände, Datenflüsse und IT-Systeme dokumentiert.
+ Intervenierbarkeit :: Betroffene Personen können ihre Rechte auf Auskunft, Berichtigung, Löschung und weitere warnehmen. Dies wird erreicht durch
	- differenzierte Einwilligungs-, Rücknahme- sowie Widerspruchsmöglichkeiten
	- Schaffung notwendiger Datenfelder z. B. für Sperrkennzeichen, Benachrichtigungen, Einwilligungen, Widersprüche, Gegendarstellungen

* IT-Sicherheit
** Gefährdung der IT-Sicherheit
** Maßnahmen gegen Gefährdung der IT-Sicherheit
** IT-Grundschutz
** Schutzbedarfsfeststellung
** IT-Sicherheitsgesetz
** Überblick IT-Sicherheit
** Verschlüsselungsverfahren
* it-Systeme
** Datensicherungskonzepte
+ Vollbackup
	- Der Speicherstand soll konsitent gesichert werden
	- File und Datenbanksicherung
	- Außerhalb der Arbeitszeiten
	- Ablauf
		+ user ausloggen
		+ Dienste stoppen
		+ Datenbank herrunter fahren
		+ Backup auf externes Medium durchführen
		+ Datenbank hoch fahren
		+ Dienste starten
	- Vorteile
		+ Nur ein File für die Herrstellung
		+ Basis für weitere Backup-Varianten
	- Nachteile
		+ Zeitintensiv
		+ hoher Speicherbedarf	
+ Differenzielles Backup
	- Ablauf
		+ Vollsicherung
		+ Alle Änderungen nach dem Letzten Vollbackup finden
	- Vorteile
		+ Speichersparend
		+ Wiederherstellungsaufwand ist Relativ gering F+D
	- Nachteile
		+ S
	- Filesicherungskonzept
+ Incremental Backup
	- Es werden nur die Änderungen seit dem letzten Backup gesichert.
	- Vorteile
		+ Schnelle umsetzung
		+ Speichersparend
	- Nachteil
		+ Hoher Wiederherstellungsaufwand (F+n*I)

*** Hardware
**** Prozessoren
Mehrprozessorsystem
Mehrkernprozessor
**** RAM
**** Festplaten
**** Schnittstellen
**** Stromversorgung
***** Schutzmaßnahmen nach DIN VDE 100-410
*** Betriebssysteme
*** Einsatzt von Cloudcomputing
*** Virtualisierung
*** Industrie 4.0
*** Anwendungssysteme
Anwendungssystem bestehen aus Software, Infrastruktur und Daten um ein bestimmtes Aufgabengebiet zu bearbeiten:
+ ERP-Systeme :: *Enterprise Resource Planning* Systeme verwalten betriebliche Ressourcen.
+ WWS-Systeme :: *Warenwirtschaftssystem* verwalten betriebliche Abläufe.
+ CRM-Systeme :: *Customer Relation Managment* Systeme unterstützen ein Unternehmen bei der Ausrichtung ihrer Geschäftsprozesse auf den Kunden.
+ SCM-Systeme :: *Supply Chain Managment* Systeme unterstüzen ein Unternehmen bei der Verwaltung der Logistik
*** RAID-Systeme
RAID steht für Redundant Array (of) independent Disks und ist ein System aus mehreren Festplatten und einem RAID-Controller. Seine Aufgabe ist es die Verfügbarkeit der Datenspeicherung zu erhöhen, indem z.B. Platten im laufenden Betrieb gewechselt und wiederhersgestellt werden können. RAID Systeme sind keine Backuplösung, da, auch wenn die Daten gespeigelt werden, Datenkompromitirungen ebenfalls gespeigelt werden und so ein wiederherstellen unmöglich machen.

RAID 0
RAID 1
RAID 5
RAID 10

** Software
*** Einordnung von Programmiersprachen
*** Pseudocode
*** Algorithmen
*** HTML und XML
*** UML-Klassendiagramm
*** UML-Use-Case-Diagramm
*** Programmablaufplan - Refactoring
*** Einordnug Datenbankaspekte
*** ER-Diagramm
*** SQL-Abfragen
*** Softwareentwicklungsprozess
*** Debugging
** Netzwerke
*** OSI-Modell, TCP/IP-Modell & Protokolle
*** WLAN
*** Gebäudeverkabelung
*** Konfiguration von IP-Adressen
*** IPv6
*** Netzwerkverkabelung - Kupferkabel
*** Fehlersuche im Netzwerk
*** Fernwartung
** Arbeits & Geschäftsprozesse
*** Das Unternehmen und sein Umfeld
**** Marktformen
|Anbieter\Nachfrager|viel Kleine|wenige Mittlere|ein Großer|
|viele Kleine|Polypol (vollständige Konkurzenz)|Nachfrageoligopol|Nachfragemonopol|
|wenige Mittlere|(Angebots-)Oligopol|bilaterales Oligopol|beschränktes Nachfragemonopol|
|ein Großer|(Angebots-)Monopol|beschränktes Angebotsmonopol|bilaterales Monopol|

+ Polypol :: Es gibt viele Anbieter viele Nachfrager. Die Anbieter stehen untereinander in vollständiger Konkurenz zueinander. Anbieter und Nachfrager haben eine geringe Marktmacht und können dadurch den Marktpreis nicht beeinflussen. 
+ Oligopol :: Es gibt wenige Anbieter und viele Nachfrager. Die Marktmacht liegt bei den Anbietern, wodurch diese direkten Einfluss auf den Martkpreis, Produktionsmenge und Güterqualität haben. Die Anbieter müssen dabei die Reaktionen der Nachfrager und ihrer Konkurenten berücksichtigen. Preissenkungen bei einem Anbieter führen so dazu das die anderen Anbieter ihre Preise ebenfalls senken müssen (Preiskampf/Verdrängungswetbewerb). Arbeiten die Anbieter hingegen zusammen, so können sie den Preis unrechtmäßig erhöhen (Kartellbildung)
+ Monopol :: Es gibt einen Anbieter und viele Nachfrager. Die gesamte Marktmacht liegt beim Anbieter, es gibt keinen Wettbewerb. Der Anbieter legt über die Nachfrage den Preis fest. Den Nachfragern bleibt nur die Möglichkeit über die Menge auf den Preis zu reagieren. Monopolisten neigen dazu den Preis nicht übermäßig zu erhöhen, da dies Konkurenz erzeugen könnte.

+ Käufermarkt :: Das Angebot ist groß, der Käufer hat mehr marktmacht und beeinflust durch seine Kaufentscheidung die Preisentwicklung nach unten.
+ Verkäufermarkt :: Die Nachfrage ist groß, der Verkäufer hat mehr marktmacht und beeinflust durch seine Verkaufsentscheidung die Preisentwicklung nach oben..

**** Wirtschaftskreislauf
Die wirtschaftlichen Zusammenhänge lassen sich als Kreislaufschema darstellen. In diesem Wirtschaftskreislauf gibt es die Aktuere Haushalt, Unternehmen, Staat, Finanzsektor und das Ausland. Zentrale Aktuere sind die Haushalte und Unternehmener. Die Haushalte tauschen bei den Unternehmen ihre Arbeitskraft gegen Gehalt, welches sie dann wieder gegen Güter bei den Unternehmen tauschen. Die Haushalte und Unternehmen zahlen an den Staat Steuern & Sozialversicherungsbeiträge und erhalten im Gegenzug Sozialleistungen und Subventionen sowie Zugang zu Gemeingütern(Schulen, Straßen, etc.). Unternehmen und Haushalte können bei den Finazsektor Geld anlegen und dafür Zinsen bekommen oder aber Kredite aufnehmen und Zinsen zahlen. Schlussendlich können Unternehmer und Haushalte ihr Geld gegen Waren und Dienstleistungen mit dem Ausland tauschen.

**** Unternehmensaufbau
+ Einlinienorganisation :: Lineare Anordnung von Anordnungs- & und Entscheidungsbefugnis. Organisationseinheiten werden nach dem Funktionsprinzip erstellt. Jede Stelle hat genau einen Vorgesetzten. Dadurch gibt es festgelegte Informations- und Entscheidungswege. Unternehmen sind selten, Behörden im Regelfall in der Einlinienorganisation angeordnet.  
	+ Vorteile
		+ Die Organisation ist leicht überschaubar.
		+ Vorgegebene Kommunikationswege und schnelle Entscheidungsfindung.
		+ Verantwortungsbereichbereiche der Stellen sind klar diffiniert.
	- Nachteile
		- Vorgegebene Kommunikationswege
		- Unflexibel bei Ausfall von höheren Linienstellen.
		- Entscheidungsträger können durch zu viele Informationen und Entscheidungen überlastet und blockiert werden.
+ Stablinienorganisation :: Die Stablinienorganisation ist einer Erweiterung der Einlinienorganisation. In der Geschäftsführungsebene unterstützt eine Reihe von Experten die oberste Linienstelle bei der Entscheidungsfindung.
	+ Vorteile
		+ Die Organisation ist leicht überschaubar.
		+ Vorgegebene Kommunikationswege und schnelle Entscheidungsfindung.
		+ Verantwortungsbereiche der Stellen sind klar diffiniert.
		+ Entscheidungsträger werden in der Entscheidungsfindung unterstüzt.
	- Nachteile
		- Vorgegebene Kommunikationswege
		- Unflexibel bei Ausfall von Entscheidungsträger.
		- Höhere Kosten
		- Abhängigkeit von den Experten
+ Mehrlinienorganisation :: Organisationseinheiten werden nach dem Funktionsprinzip erstellt.  Jede Stelle kann mehrere Vorgesetzte haben. Fachspezifische Anweisungen und Informationen könne so auf direktem Weg kommuniziert werden.
	+ Vorteile
		+ Entlastung der Entscheidungsträger.
		+ Spezialisierung der Entscheidungsträger.
		+ Flexibel bei Ausfall von Entscheidungsträger.
		+ Flexibel Kommunikationswege und schnelle Entscheidungsfindung.
	- Nachteile 
		- Verantwortungsbereiche nicht eindeutig festgelegt.
		- Wiedersprüchliche Informationen können von meheren Entscheidungsträgern gegeben werden
+ Spartenorganisation :: Bei der Spartenorganisation werden auf der zweiten Hierachieebene Organisationseinheiten, die Sparten, nach dem Objektprinzip erstellt. Alle betrieblichen Aufgaben werden durch die Sparten dezentral vom Gesamtunternehmen durchgeführt. 
	+ Vorteile
		+ Bessere Entscheidungsfindung
		+ Spezialisierung der Entscheidungsträger
		+ Bessere Beurteilung der Leistung
		+ Bessere Anpassungsfähigkeit
	- Nachteile
		- Hoher Verwaltungsaufwand
		- Bestimmte Funktionsbereiche exsistieren mehrfach
+ Matrixsorganisation :: Die Matrixsorganisation ist eine Mehrdimensionale Organisationsform. In der horizontalen Ebene wird das Unternehmen nach dem Funktionsprinzip organisiert. In der Vertikalen Ebene wird das Unternehmen nach dem Objektprinzie organisiert. An den Schnittstellen sitzen die spezifischen Abteilungen. Jede Abteilung hat eine funktionale und eine objektorientierten Entscheidungsträger.
	+ Vorteile
		+ Wegfall von Hierarchien
		+ Kurze Kommunikationswege
		+ Fördert Teamarbeit
	- Nachteile
		- Hoher Abstimmungsaufwand
		- Langsame Entscheidungsfindung
		- Kbereiche nicht eindeutig festgelegt.
**** Führungsstile
+ Autoritär :: Dieser Stil betont die Hierarchie zwischen Mitarbeitenden und der Führungskraft. Die Führungskraft gibt Entscheidungen vor, die Angestellten müssen sie entsprechend ausführen. Die Ergebnisse kontrolliert der/die Manager:in engmaschig. So entstehen eine klare Trennung und eine distanzierte Beziehung zwischen ihnen.
	+ Vorteile
		+ schnelle Entscheidungsfindung
		+ Klare Verantwortungsbereiche
	- Nachteile
		- Unterdrückt Eigeninitative im Team
		- Starke Auslastung der Führungskraft
+ Kooperativ :: Dieser Führungsstil wird oft auch als demokratisch bezeichnet. Denn hier bezieht die Führungskraft ihre Teammitglieder bei Entscheidungen mit ein. Entsprechend liegt der Fokus auf eigenverantwortlichem Handeln und Eigenkontrolle der Mitarbeitenden.
	+ Vorteile
		+ Entlastung der Führungskraft
		+ Gesteigertes Verantwortungsbewussein im Team
	- Nachteile
		- Langsame Entscheidungsfindung
		- Entscheidungen des Verantwortlichen können übergangen werden
+ Laissez-Faire :: Der Name ist Programm – die Angestellten haben komplette Freiheit und bestimmten ihre Aufgaben selbst. Die Führungskraft lässt sie komplett gewähren. Entscheidungen fällt das Team gemeinsam.
	+ Vorteile
		+ Mitarbeiter setzen ihre individuelle Fähigkeiten ein
	+ Nachteile
		- Fehlende Koordination und Absprache
		- Orientriung fehlt

**** Führungstechniken
+ Managment by Delegation :: Führende delegieren komplette Aufgaben und geben konkrete Ziele vor.
	+ Vorteile
		+ Mehr Mitarbeitermotivation durch Übertragung von Verantwortung
		+ Einbeziehung der Mitarbeiter in die unternehmerischen Ziele
		+ Stärkere Bindung der Mitarbeiter an das Unternehmen
		+ Entlastung der Führenden
		+ Beseitigung starrer Hierarchie und Entscheidungsbefugnisse
	- Nachteile
		- Regelmäßige Kontrolle der Mitarbeiter notwendig
		- Kontrolle kann auf Beschäftigte demotivierend wirken
		- Übertragung von Routineaufgaben kann demotivierend wirken
		- Gefahr von Unterforderung als auch Überforderung
		- Aufgaben werden evtl. nicht wie gewünscht umgesetzt
+ Managment by Objectives :: Führende und Geführte erarbeiten gemeinsam Ziele für konkrete Aufgaben.
	+ Vorteile
		+ Integration der Mitarbeiter in Zielsetzungsprozesse
		+ Mitarbeitermotivation durch mehr Verantwortung und Boni
		+ Stärkere Mitarbeiterbindung
		+ Verknüpfung von Zielen der Organisation und individuellen Zielen
		+ Entlastung von Führungskräften
	- Nachteile
		- Führungskräfte müssen Kontrollaufgaben übernehmen
		- Steigender Leistungsdruck für Mitarbeiter durch Zielvorgabe
		- Funktioniert ohne Anreizsystem nicht
		- Gefahr, dass sich Mitarbeiter nur auf persönliche Ziele fokussieren und das Gesamtbild aus dem Auge verlieren
		- Durch die Zielfokussierung steigt die Gefahr, dass qualitative Aspekte der Arbeit vernachlässigt werden
+ Managment by Exception :: Der Führende greift nur in Ausnahmefällen ein und hält sich in Normalfällen zurück.
	+ Vorteile
		+ Entlastung der Führungskräfte von Routineaufgaben
		+ Geringerer Kontrollaufwand als bei anderen Management by Techniken
		+ Höhere Motivation der Mitarbeiter durch selbstständige Arbeit in ihren Kompetenzbereichen
	- Nachteile
		- Mitarbeiter können dazu neigen, schlechte Ergebnisse zu verschleiern
		- In der Regel Beschränkung der Mitarbeiter auf Routineaufgaben
		- Richtige Balance zwischen Eingriffen und Eigenverantwortung ist eine Herausforderung.
		- Unzureichende Kontrollen können zu schlechten Ergebnissen führen
+ Managment by Decision Rules :: Ein Regelwerk schreibt den Geführten nach dem „Wenn-Dann-Prinzip“ vor, was in bestimmten Situationen zu tun ist.
	+ Vorteile
		+ Deutliche Entlastung der Führenden insbesondere von Routineaufgaben
		+ Steuerung und Kontrolle von Mitarbeiterverhalten wird durch festes Regelwerk vereinfacht
		+ Unternehmensziele und (Routine-) Aufgaben können sehr gut aufeinander abgestimmt werden
	- Nachteile
		- Beschränkung des Führungskonzepts auf Routineaufgaben
		- Das Regelwerk kann nicht alle möglichen Szenarien abdecken
		- Starke Formalisierung und Strukturierung der Arbeit durch einfache Regeln
		- Fehlende Motivation der Mitarbeiter, da Eigenverantwortung durch ein starres Regelwerk ersetzt wird
+ Managment by Systems :: Ganzheitliche Methode, die verschiedene Management by Techniken einsetzt, mit der alle Abläufe eines Unternehmens optimiert werden können.
	+ Vorteile
		+ Entlastung der Führungskräfte insbesondere durch Routineaufgaben
		+ Optimierung von Arbeitsabläufen vor allem im Verwaltungsbereich
		+ Kostenreduktion insbesondere im Verwaltungskontext
		+ Klare Regeln und Strukturen auf allen Ebenen vereinfachen die Kommunikation
	- Nachteile
		- Höherer Grad an Bürokratie
		- Schwierige Implementierung
		- Fehlende Flexibilität in Ausnahmesituationen oder bei Innovationsprozessen
		- Demotivation von Mitarbeitern durch kaum vorhandene Eigenverantwortung und ein starres Regelsystem

*** Unternehmensziele und Wirdschaftlichkeitsüberlegungen
Das Unternehmensleitbild beschreibt das Selbstverständnis eines Unternhemens.
*** Prozesse im Unternehmen - der Beschaffungsprozess
*** Beschaffungs- und Absatz-Prozesse im Unternehmen - rechtliche Hintergründe
*** Auftragseingangprozesse im Unternehmen und Preisbildung
